export default {
  REGISTER: "/ai/draw/login/register",
  GET_VERIFY_CODE: "/ai/draw/login/send/verify/code",
  PWD_LOGIN: "/ai/draw/login/account/login",
  PHONE_LOGIN: "/ai/draw/login/account/login/phone",
  GET_BOOKMARK_LIST: "/ai/draw/picture/clip/get/list",
  LOGOUT: "/ai/draw/login/account/logout",
  QUERY_IMG: "/ai/draw/picture/get/page",
  QUERY_KEYWORDS: "/ai/draw/picture/get/keyword/tree",
  TEXT2IMG: "/ai/draw/picture/ai/txt2img",
  ADD_NEW_BOOKMARK: "/ai/draw/picture/clip/add",
  IMG_REFRESH: "/ai/draw/picture/ai2img/refresh",
  IMG2IMG: "/ai/draw/picture/ai/img2img",
  COLLECT_IMG: "/ai/draw/picture/collect",
  CANCEL_COLLECT_IMG: "/ai/draw/picture/cancel/collect",
  SET_PICTURE: "/ai/draw/picture/update",
  CLIP_PICTURES: "/ai/draw/picture/clip/get/detail",
  PERSONAL_INFO: "/ai/draw/account/get/detail",
  WELCOME: "/ai/draw/statistic/system/used",
  FOCUS: "/ai/draw/account/focus/account",
  UN_FOCUS: "/ai/draw/account/cancel/focus/account",
  FOCUS_LIST: "/ai/draw/account/get/page/focus",
  RENAME_CLIP: "/ai/draw/picture/clip/update",
  DELETE_CLIP: "/ai/draw/picture/clip/delete",
  EDIT_USER: "/ai/draw/account/update",
  VERIFY_CODE: "/ai/draw/login/check/verify/code",
  GET_LIST: "/ai/draw/dict/get/list"
}